### ISSUE TITLE
Is there any way to use this library with Java 7

### ISSUE THREAD

**Issue by ahmednrana** [ctabin/jotlmsg#92]
My company is still using Java 7. Is there any way to use this library or any of its older versions with Java 7?

**Comment by ctabin** [comment]
Hi @ahmednrana,

I'm afraid not by using the artifacts on maven, since I've compiled them with the JDK8 and with JDK11 since recently.
So your only option is to do the compilation yourself with the sources. Since you are with the JDK7, you'll probably have some issues with the jakarta package, so I advise you to checkout the [release 1.8](https://github.com/ctabin/jotlmsg/releases/tag/jotlmsg-1.8) and change the needed settings in the `pom.xml`.
